// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnfliuobpkyzrwwnnvfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpuZmxpdW9icGt5enJ3d25udmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjY4MDgsImV4cCI6MjA1OTU0MjgwOH0.JqZA-KdBp30_1ZsyzxTFLsYh_4TW6594G7wArE0NTRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);